### ISSUE TITLE
Random crash after attack

### ISSUE THREAD

**Issue by cwild** [bcavill/game#1]
During the game, an attack sometimes crashes the game.

Here is the stacktrace:

```chris@goliath:/tmp/game$ python game.py 
What is thy name brave warrior? chris
Greetings chris, a trol is attacking our village please help us.
What should you do? ['Attack', 'Use an item'] attack
Now attacking trol Dorizin
player chris attacked trol Dorizin
player chriss' attack missed 

Traceback (most recent call last):
  File "game.py", line 82, in <module>
    Game.new_game()
  File "game.py", line 21, in new_game
    self.loop()
  File "game.py", line 47, in loop
    self.char.target.attack()
  File "/tmp/game/characters.py", line 25, in attack
    print '%s %s attacked %s %s' % (self.__class__.__name__, self.name, self.target.__class__.__name__, self.target.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by bcavill** [comment]
Fixed in commit cf82c6e.
